ITEM.name = "Consumables Permit"
ITEM.desc = "A piece of paper that allows one to sell consumable goods."
ITEM.model = "models/props_lab/clipboard.mdl"
ITEM.category = "Permits"
ITEM.flag = "y"
ITEM.uniqueID = "permit_food"